"if you want to set configure for all users,
"make file /etc/vim/vimrc.local 

syntax enable
filetype plugin indent on
set number
set tabstop=4
set shiftwidth=4
set hlsearch
"set expandtab

"Auto complete config
hi Pmenu ctermfg=white ctermbg=245
hi PmenuSel ctermfg=lightgrey ctermbg=darkblue 

"Highlight color
hi Search cterm=NONE ctermbg=darkgrey ctermfg=white

"Visual color
hi Visual cterm=NONE ctermbg=darkgrey ctermfg=darkcyan

"Command
:command W w
:command Wq wq
:command Q q
:command WQ wq

"Markdown highlighting
augroup markdown
	" remove previous autocmds
	autocmd!

	" set every new or raed *.md buffer to use the markdown filetype
	autocmd BufRead,BufNew *.md set filetype=markdown

augroup END
